//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversidadEntidades : DbContext
    {
        public UniversidadEntidades()
            : base("name=UniversidadEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Asignatura> Asignatura { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Carrera_Asignatura> Carrera_Asignatura { get; set; }
        public virtual DbSet<Estu_Asig> Estu_Asig { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<EstudianteLogs> EstudianteLogs { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Profesor_Asignatura> Profesor_Asignatura { get; set; }
    }
}
